
package Proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BankAccountService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankAccountService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertionEuroToDh", targetNamespace = "http://ws/", className = "Proxy.ConvertionEuroToDh")
    @ResponseWrapper(localName = "convertionEuroToDhResponse", targetNamespace = "http://ws/", className = "Proxy.ConvertionEuroToDhResponse")
    @Action(input = "http://ws/BankAccountService/convertionEuroToDhRequest", output = "http://ws/BankAccountService/convertionEuroToDhResponse")
    public double convertionEuroToDh(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.util.List<Proxy.Account>
     */
    @WebMethod(operationName = "ListAccounts")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ListAccounts", targetNamespace = "http://ws/", className = "Proxy.ListAccounts")
    @ResponseWrapper(localName = "ListAccountsResponse", targetNamespace = "http://ws/", className = "Proxy.ListAccountsResponse")
    @Action(input = "http://ws/BankAccountService/ListAccountsRequest", output = "http://ws/BankAccountService/ListAccountsResponse")
    public List<Account> listAccounts();

    /**
     * 
     * @param code
     * @return
     *     returns Proxy.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://ws/", className = "Proxy.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://ws/", className = "Proxy.GetAccountResponse")
    @Action(input = "http://ws/BankAccountService/getAccountRequest", output = "http://ws/BankAccountService/getAccountResponse")
    public Account getAccount(
        @WebParam(name = "code", targetNamespace = "")
        int code);

}
